# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: /go/src/github.com/marcopollivier/go-simple-icons
    environment:
      TEST_RESULTS: /tmp/test-results
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go vet ./...
      - run: go test ./...
